publishDir="public"

# Your domain name. Must end with "/"
baseURL                     = "https://kolmoblocks.github.io"
# languageCode
languageCode                = "en-us"
# Site title
title                       = "Kolmoblocks: self-describing data encoding"
theme = "hon"

# https://help.farbox.com/pygments.html
pygmentsStyle               = "monokai"
pygmentsCodefences          = true
enforce_ssl                 = false


# Enable Disqus for comments https://gohugo.io/content-management/comments
# disqusshortname           = ""
# Enable Google Analytics https://gohugo.io/templates/internal/#google-analytics
# googleAnalytics           = ""
[params.config]
    # Choose 'light' or 'dark'
    theme                   = "light"
    # Include custom css files e.g. ["css/foo.css", "css/bar.css"]
    customCSS               = []
    # Turn on/off the fade-in effect
    fadeEffect              = true
    # Max 160 characters show in search results
    description             = "HON Project"
    # faviconFile             = "img/fav.ico"
    faviconFile             = ""
    # Add the current unix timestamp in query string for cache busting css
    # assets (relevant in development mode)
    cacheBuster             = false
    # Date format
    dateFormat              = "Jan 2, 2006"
    # Date full format
    dateFullFormat          = "Mon Jan 2 2006 15:04:05 EST"
    # Choose size of Hero Section.
    # Input either 'medium' or 'large' or 'fullheight'
    heroHeight              = "fullheight"
    # Title
    heroTitle               = "KolmoLD"
    # a tagline for the title
    heroSubtitle            = "self-describing data encoding for Merkle DAG"

# activating different components of the website
[params.components]
    about                   = true
    documentation           = true
    summary                 = true

# Creating menus
[menu]
[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    weight = 10
    identifier = "documentation"
    url = "/documentation/about"
[[menu.main]]
    name = "Article"
    pre = "<i class='fa fa-heart'></i>"
    weight = 20
    identifier = "documentation"
    url = "/documentation/article"
[[menu.main]]
    name = "Resources"
    pre = "<i class='fa fa-road'></i>"
    weight = 30
    url = "/documentation/learning_resources"