name = "hon"
description = "Minimal, single page, smooth scrolling theme for Hugo."
tags = ["clean", "simple", "minimal", "minimalist", "responsive", "single page", "syntax highlighting", "projects", "starter", "white", "dark"]
features = ["responsive", "blog", "portfolio"]
min_version = "0.44"

